name: Electron Publish

on:
  release:
    types: [ created ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  version:
    name: Version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.result }}
    steps:
      - uses: actions/github-script@441359b1a30438de65712c2fbca0abe4816fa667
        id: version
        with:
          script: |
            const semver = context.ref.replace('refs/tags/v', '')
            if (semver.match(/^[0-9]+\.[0-9]+\.[0-9]+$/)) {
              return semver
            }

            throw new Error('not semver')
          result-encoding: string

  publish_linux_app:
    runs-on: ubuntu-latest
    needs: [ version ]
    steps:
      - uses: actions/checkout@1e204e9a9253d643386038d443f96446fa156a97
      - uses: actions/setup-node@270253e841af726300e85d718a5f606959b2903c
        with:
          node-version: 16

      - run: npm ci

      - run: |
          git config --global user.email "github-bot@defichain.com"
          git config --global user.name "defichain-bot"
          npx standard-version --release-as ${{ needs.version.outputs.version }}

      - name: Publish app
        working-directory: ./desktop-app
        run: npm run publish
        env:
          GITHUB_TOKEN: ${{ secrets.DEFICHAIN_BOT_GITHUB_TOKEN }}

  create-linux-checksum:
    needs: [ version, publish_linux_app ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1e204e9a9253d643386038d443f96446fa156a97
      - uses: actions/setup-node@270253e841af726300e85d718a5f606959b2903c
        with:
          node-version: 16

      - name: Fetch Release Asset
        uses: Legion2/download-release-action@68df3d242858e28a7e6d8b9838a3e6730cdfc422
        with:
          repository: 'DeFiCh/wallet'
          tag: 'v${{ needs.version.outputs.version }}'
          file: 'DeFiChain-Wallet-${{needs.version.outputs.version}}.AppImage'

      - name: Generate SHA256 checksum
        run: |
          sha256sum DeFiChain-Wallet-${{needs.version.outputs.version}}.AppImage > DeFiChain-Wallet-${{needs.version.outputs.version}}.AppImage.SHA256

      - name: Upload checksum - Linux
        uses: softprops/action-gh-release@a80139913ad69754b738283897e8a1e3362b1a03
        with:
          fail_on_unmatched_files: true
          files: ./DeFiChain-Wallet-${{needs.version.outputs.version}}.AppImage.SHA256
          token: ${{ secrets.DEFICHAIN_BOT_GITHUB_TOKEN }}

  publish_mac_app:
    environment: Electron Release
    runs-on: macos-latest
    needs: [ version ]
    steps:
      - uses: actions/checkout@1e204e9a9253d643386038d443f96446fa156a97
      - uses: actions/setup-node@270253e841af726300e85d718a5f606959b2903c
        with:
          node-version: 16

      - run: npm ci

      - run: |
          git config --global user.email "github-bot@defichain.com"
          git config --global user.name "defichain-bot"
          npx standard-version --release-as ${{ needs.version.outputs.version }}

      - name: Publish app
        working-directory: ./desktop-app
        run: npm run publish
        env:
          GITHUB_TOKEN: ${{ secrets.DEFICHAIN_BOT_GITHUB_TOKEN }}
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          CI: true
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASS: ${{ secrets.APPLE_ID_PASS }}

  create-mac-checksum:
    needs: [ version, publish_mac_app ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1e204e9a9253d643386038d443f96446fa156a97
      - uses: actions/setup-node@270253e841af726300e85d718a5f606959b2903c
        with:
          node-version: 16

      - name: Fetch Release Asset
        uses: Legion2/download-release-action@68df3d242858e28a7e6d8b9838a3e6730cdfc422
        with:
          repository: 'DeFiCh/wallet'
          tag: 'v${{ needs.version.outputs.version }}'
          file: 'DeFiChain-Wallet-${{needs.version.outputs.version}}.dmg'

      - name: Generate SHA256 checksum
        run: |
          sha256sum DeFiChain-Wallet-${{needs.version.outputs.version}}.dmg > DeFiChain-Wallet-${{needs.version.outputs.version}}.dmg.SHA256

      - name: Upload checksum - Mac
        uses: softprops/action-gh-release@a80139913ad69754b738283897e8a1e3362b1a03
        with:
          fail_on_unmatched_files: true
          files: ./DeFiChain-Wallet-${{needs.version.outputs.version}}.dmg.SHA256
          token: ${{ secrets.DEFICHAIN_BOT_GITHUB_TOKEN }}

  publish_windows_app:
    runs-on: windows-latest
    needs: [ version ]
    steps:
      - uses: actions/checkout@1e204e9a9253d643386038d443f96446fa156a97
      - uses: actions/setup-node@270253e841af726300e85d718a5f606959b2903c
        with:
          node-version: 16

      - run: npm ci

      - run: |
          git config --global user.email "github-bot@defichain.com"
          git config --global user.name "defichain-bot"
          npx standard-version --release-as ${{ needs.version.outputs.version }}

      - name: Publish app
        working-directory: ./desktop-app
        run: npm run publish
        shell: powershell
        env:
          GITHUB_TOKEN: ${{ secrets.DEFICHAIN_BOT_GITHUB_TOKEN }}

  create-windows-checksum:
    needs: [ version, publish_windows_app ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1e204e9a9253d643386038d443f96446fa156a97
      - uses: actions/setup-node@270253e841af726300e85d718a5f606959b2903c
        with:
          node-version: 16

      - name: Fetch Release Asset
        uses: Legion2/download-release-action@68df3d242858e28a7e6d8b9838a3e6730cdfc422
        with:
          repository: 'DeFiCh/wallet'
          tag: 'v${{ needs.version.outputs.version }}'
          file: 'DeFiChain-Wallet-Setup-${{ needs.version.outputs.version }}.exe'

      - name: Generate SHA256 checksum
        run: |
          sha256sum DeFiChain-Wallet-Setup-${{ needs.version.outputs.version }}.exe > DeFiChain-Wallet-Setup-${{ needs.version.outputs.version }}.exe.SHA256

      - name: Upload checksum - Windows
        uses: softprops/action-gh-release@a80139913ad69754b738283897e8a1e3362b1a03
        with:
          fail_on_unmatched_files: true
          files: ./DeFiChain-Wallet-Setup-${{ needs.version.outputs.version }}.exe.SHA256
          token: ${{ secrets.DEFICHAIN_BOT_GITHUB_TOKEN }}
